services:
  stock_watcher:
    container_name: stock_watcher
    image: odumag99/stock_watcher:latest
    pull_policy: always
    env_file:
      - .env
    volumes:
      - ./stock_watcher.db:/app/stock_watcher.db:rw